import { MessagesProvider } from "@/context/MessageContext";
import "./globals.css";
import Provider from './provider';
import ConvexClientProvider from './ConvexClientProvider';

export const metadata = {
  title: "AIDevX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ConvexClientProvider>
    <Provider>
    <MessagesProvider>
      <html lang="en" suppressHydrationWarning>
      <body>
          {children}
      </body>
    </html>
    </MessagesProvider>
    </Provider>
    </ConvexClientProvider>
  );
}
